// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZGQQixBx_-w9NuYR32Fmv4fsdR57wLc',
    appId: '1:702083419047:web:dffd46b9239411c930c482',
    messagingSenderId: '702083419047',
    projectId: 'task-cpf',
    authDomain: 'task-cpf.firebaseapp.com',
    storageBucket: 'task-cpf.firebasestorage.app',
    measurementId: 'G-M4QX90FXV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTF3jjbiD8HcxNPWDldjorLd69f2E5Lw',
    appId: '1:702083419047:android:a455ab5021dc023e30c482',
    messagingSenderId: '702083419047',
    projectId: 'task-cpf',
    storageBucket: 'task-cpf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGKhUZ_Z3p6vtwFfilMQiA-HrfNHBDJgM',
    appId: '1:702083419047:ios:b9423bbb7df09cbe30c482',
    messagingSenderId: '702083419047',
    projectId: 'task-cpf',
    storageBucket: 'task-cpf.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGKhUZ_Z3p6vtwFfilMQiA-HrfNHBDJgM',
    appId: '1:702083419047:ios:b9423bbb7df09cbe30c482',
    messagingSenderId: '702083419047',
    projectId: 'task-cpf',
    storageBucket: 'task-cpf.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ZGQQixBx_-w9NuYR32Fmv4fsdR57wLc',
    appId: '1:702083419047:web:dedb95c8b8d5dcb630c482',
    messagingSenderId: '702083419047',
    projectId: 'task-cpf',
    authDomain: 'task-cpf.firebaseapp.com',
    storageBucket: 'task-cpf.firebasestorage.app',
    measurementId: 'G-X5XL1G94Q7',
  );
}
